# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: My Theme
  theme_night: My Theme
  font: classic
  font_size: L
  
require_fancybox: true
# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: 'Musician'
    org_name: 'Timothy Rosenberg: Saxophonist, Teacher, Technologist'
    description: 'Timothy Rosenberg is a saxophonist based in Orlando, FL. He is currently the Visisting Assistant Professor of Saxophone at Stetson University. He teaches saxophone, music technology, jazz improvisation, and is the Director of the Stetson Summer Saxophone Workshop.'
    twitter: 'timrosenberg'
  analytics:
    google_analytics: ''
  verification:
    google: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Timothy Rosenberg. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  #syntax_highlighter:
    #theme_light: github-light
    #theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
